name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build packageRelease

      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: SharedHP-release
          path: build/release/
